http:
  host: "0.0.0.0"
  port: "8080"
  timeout: 4s
  idle_timeout: 30s
grpc:
  is_able: false
prometheus:
  is_able: false
database:
  protocol: "postgres"
  host: "db"
  port: "5432"
  user: "postgres"
  password: "postgres"
  name: "pvz"
jwt:
  secret: "Wrong way to put this away"
  expires_in: 24h